# Generated by Django 5.1.4 on 2024-12-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField()),
                ('poster_path', models.CharField()),
                ('vote_average', models.FloatField()),
            ],
            options={
                'db_table': 'favorite_movies',
            },
        ),
    ]
