# Generated by Django 5.1.4 on 2024-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_watchlisted',
            field=models.BooleanField(default=False),
        ),
    ]
