# Generated by Django 5.1.4 on 2024-12-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='watchlist',
            table='watchlist_movies',
        ),
    ]
