# Generated by Django 5.1.4 on 2024-12-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_movie', '0002_alter_watchlist_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='WatchlistMovie',
        ),
    ]
